### ISSUE TITLE
PR- 审批节点分配人员或者group由下拉框改成带选择功能的弹出框

### ISSUE THREAD

**Issue by buzzlu** [guozhaolong/wfd-vue#11]
hello：

我关注这个组件有段时间了，觉得很不错，从做工作流的经验来看，审批节点分配常见的有，人员，角色，以及对应的部门负责人等，常规角色和对应的部门可以抽象成group。

通常来说，待选择人员或者group很多，如果能改成带筛选功能的弹出框，易用性会更高些，角色和部门负责人这两个分类能再细分单列出来，更好。

请考虑下这个需求。谢谢。

**Comment by guozhaolong** [comment]
ok，我改一下

**Comment by buzzlu** [comment]
谢谢

**Comment by guozhaolong** [comment]
我正在重构这个设计器，过一阵会出个新版本
