### ISSUE TITLE
vue-typescript-admin-template 项目中引入wfd-vue 错

### ISSUE THREAD

**Issue by buzzlu** [guozhaolong/wfd-vue#14]
我在vue-typescript-admin-template 项目中引入wfd-vue（https://github.com/Armour/vue-typescript-admin-template），遇到以下依赖错，

实际上我已经安装了@antv/g6包，

 ERROR  Failed to compile with 3 errors                                                             8:28:06 PM
These dependencies were not found:

* @antv/g6/src in ./node_modules/wfd-vue/dist/wfd-vue.umd.min.js
* @antv/g6/src/item/item in ./node_modules/wfd-vue/dist/wfd-vue.umd.min.js
* @antv/g6/src/shape/single-shape-mixin in ./node_modules/wfd-vue/dist/wfd-vue.umd.min.js

To install them, you can run: npm install --save @antv/g6/src @antv/g6/src/item/item @antv/g6/src/shape/single-shape-mixin

这个错是wfd-vue自身引用造成的还是我引入的方式不对？

谢谢。

**Comment by Groundhog-Chen** [comment]
崩溃~我也是这个错！

**Comment by guozhaolong** [comment]
你们指定一下你项目的package.json的g6版本为~3.1.3试试，这个错误是因为g6后面3.3+的版本没有src目录和G6.Shape对象造成的
