### ISSUE TITLE
运行 npm run build-example 时报错

### ISSUE THREAD

**Issue by w306621759** [guozhaolong/wfd-vue#19]
![image](https://user-images.githubusercontent.com/4316813/80064669-2c553d00-856b-11ea-8712-bc551768656c.png)

你好，我clone项目下来在本地运行npm run serve 可以正常工作，但是我运行
npm run build-example 时，报错，如上截图

**Comment by guozhaolong** [comment]
不知道啊，是不是因为没有docs目录啊，你不运行build-example不就没事啦
