### ISSUE TITLE
太给劲了

### ISSUE THREAD

**Issue by a-tony** [guozhaolong/wfd-vue#2]
大佬，这个工作流终于有vue的了，太给劲了，崇拜你

**Comment by guozhaolong** [comment]
哈哈

**Comment by Shaxin742** [comment]
我在mounted给流程图赋值后  页面不显示  开始我以为是vue版本问题但是在把vue版本设置为^2.6.10 后 再重新run 页面显示了却不能点击 托抓后消失 求解答

**Comment by slyang520** [comment]
@guozhaolong   感谢老哥,比JAVA开源项目编辑器的好看很多。   给了一个改造思路 👍

**Comment by a-tony** [comment]
我把你的编辑器集成到我系统里面，还是有很多地方有问题的，等我一 一列举出来给您，您应该丰富您的编辑器，让更多的人使用，这样你就是红人了

**Comment by guozhaolong** [comment]
@a-tony 非常感谢，期待你的反馈啊
