### ISSUE TITLE
怎样动态选在节点显示的锚点数？

### ISSUE THREAD

**Issue by wrh4585** [guozhaolong/wfd-vue#24]
请教一下，怎么动态配置节点显示的锚点信息，目前项目中节点显示的锚点数是在配置文件中固定的，不同类型的节点有不同的锚点数目。
考虑实现这一一个功能，通过一个下拉框，将节点需要显示的锚点数动态更新到节点上。下拉框选定的值以后，将对应的锚点数的树组传入，数组中每个元素未锚点的位置信息，然后再更新节点。目前想到的做法是选择下拉框时，将图上的node节点获取到，遍历获取到的node节点数组，给每个节点的model中添加anchorPoints为选择的锚点数组，然后更新node，但是并不生效。。。
请教下应该怎么实现这种功能？

**Comment by guozhaolong** [comment]
原因getAnchorPoints已经被我写死在代码里只能返回固定的数组了，你可以把getAnchorPoints方法去掉，然后他就会触发这段G6的代码了
`getAnchorPoints(cfg: ModelConfig): number[][] | undefined {`
      `const { anchorPoints: defaultAnchorPoints } = this.options as ModelConfig;`
      `const anchorPoints = cfg.anchorPoints || defaultAnchorPoints;`
      `return anchorPoints;`
`}`

**Comment by wrh4585** [comment]
> 原因getAnchorPoints已经被我写死在代码里只能返回固定的数组了，你可以把getAnchorPoints方法去掉，然后他就会触发这段G6的代码了
> `getAnchorPoints(cfg: ModelConfig): number[][] | undefined {`
> `const { anchorPoints: defaultAnchorPoints } = this.options as ModelConfig;`
> `const anchorPoints = cfg.anchorPoints || defaultAnchorPoints;`
> `return anchorPoints;`
> `}`

好的，我试试去，谢谢啦

**Comment by wrh4585** [comment]
已经实现这个功能，修改绘制锚点的方法，然后确保在选择了锚点数后，能获取到数据中的anchorPoints即可。

**Comment by guozhaolong** [comment]
nice

**Comment by wrh4585** [comment]
G6升级到3.5.2版本后，参照wfd项目中的写法，默认显示的示例功能是正常的，但是节点无法拖动到画布中，原来3.1.3版本中，增加节点时，需要在flowNode.js中注册节点的类型，然后还需要定义对应的vue组件。但是实际后，拖动节点到画布中不显示节点，开始以为是节点被挡住了，但是调用save（）方法，发现G6的实例数据中没有加进去节点。
感觉升级后，又要从头开始进行了。。。
请教下，大佬G6版本升级后，这块应该怎么实现？

tips:app.vue 文件中数据可以正常渲染，但是左侧边栏中的节点均无法显示。
github 不能回复，所以用邮件回复了，sorry~~~





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Steven Kwok"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月29日(星期一) 上午9:53
收件人:&nbsp;"guozhaolong/wfd-vue"<wfd-vue@noreply.github.com&gt;;
抄送:&nbsp;" LookingForW"<724517590@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [guozhaolong/wfd-vue] 怎样动态选在节点显示的锚点数？ (#24)





 
nice

**Comment by guozhaolong** [comment]
behavior下面有个dragPanelItemAddNode.ts，这是拖动节点进来的实现，115行是增加节点到画布的代码，你打印一下试试

**Comment by wrh4585** [comment]
问题解决了，是在addItemPanel.js中，修改文件的时候，class类写的有问题，造成没有获取到children。
