### ISSUE TITLE
antv g6 能升级到最新版本吗

### ISSUE THREAD

**Issue by acodeman** [guozhaolong/wfd-vue#28]
antv g6 能升级到最新版本吗? 现在的antv g6版本太低了，已经找不到官方文档了

**Comment by guozhaolong** [comment]
ok，react已经升级到新版了，vue的我马上搞一下

**Comment by acodeman** [comment]
非常感谢

**Comment by qianzhangsheng** [comment]
支持大佬升级

**Comment by huangpna** [comment]
![image](https://user-images.githubusercontent.com/34829633/96684584-62ef0180-13ae-11eb-9b47-479a0ee1acc4.png)
版本升级后报错怎么处理？

**Comment by huangpna** [comment]
之前是2.2.6的版本

**Comment by guozhaolong** [comment]
你调用的这个registerGuide好像不暴露出来了，你看一下他们的文档

**Comment by huangpna** [comment]
好的  谢谢 那我再看看。
