### ISSUE TITLE
大佬有升级G6的计划吗？

### ISSUE THREAD

**Issue by qianzhangsheng** [guozhaolong/wfd-vue#33]
发现升级到G6 3.5.12 以后很多API都无法运行了

**Comment by guozhaolong** [comment]
我最近在忙公司的开发工作，有时间一定会升级到新版本的

**Comment by qinzitong** [comment]
> 我最近在忙公司的开发工作，有时间一定会升级到新版本的

我已经按照 react的版本升级vue版本了，我可以贡献一下代码吗？

**Comment by guozhaolong** [comment]
> > 我最近在忙公司的开发工作，有时间一定会升级到新版本的
> 
> 我已经按照 react的版本升级vue版本了，我可以贡献一下代码吗？

可以啊，非常感谢

**Comment by qinzitong** [comment]
> > > 我最近在忙公司的开发工作，有时间一定会升级到新版本的
> > 
> > 
> > 我已经按照 react的版本升级vue版本了，我可以贡献一下代码吗？
> 
> 可以啊，非常感谢

已经提交提交 request

**Comment by guozhaolong** [comment]
> > > > 我最近在忙公司的开发工作，有时间一定会升级到新版本的
> > > 
> > > 
> > > 我已经按照 react的版本升级vue版本了，我可以贡献一下代码吗？
> > 
> > 
> > 可以啊，非常感谢
> 
> 已经提交 request

已合并到master分支，多谢兄弟
