### ISSUE TITLE
打包出来什么都没有？

### ISSUE THREAD

**Issue by LiangQinAo** [guozhaolong/wfd-vue#36]

**Comment by guozhaolong** [comment]
应该是报错了吧？

**Comment by Liang-aj** [comment]
Uncaught ReferenceError: wfd is not defined

然后页面就是空白的

**Comment by Liang-aj** [comment]
DevTools failed to load SourceMap: Could not load content for file:///Users/aoliang/Downloads/wfd-vue-master/dist/hierarchy.js.map: System error: net::ERR_FILE_NOT_FOUN

还有这个

**Comment by Liang-aj** [comment]
现在是还不能打包发布吗。。

**Comment by qinzitong** [comment]
你首先看看打包完了看看dist 目录下面有没有 文件，如果有的话，就是打包的问题了，就是你自己改的配置出了问题了

**Comment by Liang-aj** [comment]
> 你首先看看打包完了看看dist 目录下面有没有 文件，如果有的话，就是打包的问题了，就是你自己改的配置出了问题了

后来发现，是不能用build打包。。只能用build-example。
build打包出来是啥都没的
