### ISSUE TITLE
同类项目，可否增加一个友链？

### ISSUE THREAD

**Issue by GoldSubmarine** [guozhaolong/wfd-vue#40]
之前也给这个项目提了一些 PR，但是仍然遇到一些痛点，最后还是放弃了，比如：

- 节点类型不全，节点类型实在太多了，全部自定义一遍太费劲了
- 面板属性不全，无法满足我司的业务需求
- 面板属性转 xml 是依靠字符串拼接，容易出错
- 必须把 g6 的节点信息交给后端存储，这样才能再次编辑，因为无法逆向解析 xml

最后我写了一个新的 modeler，直接基于 bpmn.io ，目前功能已经比较全面了，兄台可否在readme增加一个友链，相信能帮助到不少人。

[https://github.com/GoldSubmarine/workflow-bpmn-modeler](https://github.com/GoldSubmarine/workflow-bpmn-modeler)

**Comment by guozhaolong** [comment]
ok，没问题
