### ISSUE TITLE
G6升级到3.7.0了，好像偷偷改了API，然后点击节点就报错了

### ISSUE THREAD

**Issue by qianzhangsheng** [guozhaolong/wfd-vue#45]
G6升级到3.7.0了，好像偷偷改了API，然后点击节点就报错了

G6都不说改什么API，太万恶了😩

**Comment by guozhaolong** [comment]
啥错误啊？我改为3.7.0没啥问题

**Comment by qianzhangsheng** [comment]
<img width="1200" alt="WX20200827-081629@2x" src="https://user-images.githubusercontent.com/1262247/91369280-fd631680-e83d-11ea-8370-b3a49cb72047.png">
<img width="1203" alt="WX20200827-081556@2x" src="https://user-images.githubusercontent.com/1262247/91369284-ffc57080-e83d-11ea-8022-7f6365c777cc.png">

升级到3.7.0以后光标移到nodes的4个连接点上就会报错

**Comment by guozhaolong** [comment]
我刚看到我只用到了3.6.2，3.7.0当时还没打包呢。。。我去试一下

**Comment by guozhaolong** [comment]
我试了3.7.0没出现你说的这种报错情况啊

**Comment by qianzhangsheng** [comment]
> 我试了3.7.0没出现你说的这种报错情况啊

@antv/g-canvas 这个组件大佬有升级吗？

**Comment by guozhaolong** [comment]
我用wfd试的没报错，vue的没试。。。

**Comment by qinzitong** [comment]
3.6.2 的时候 hoverAnchorActived 的那个点就不生效了，没有变成实心的蓝色点，3.7.0 也是这样；3.5.2 没有问题

**Comment by qinzitong** [comment]
g6 升级了
maker.js 单独拆出来了

**Comment by guozhaolong** [comment]
对，hoverNodeActived那块改成e.target.cfg.type === 'marker'来做判断了，之前是e.target instanceof Marker

**Comment by qinzitong** [comment]
> 对，hoverNodeActived那块改成e.target.cfg.type === 'marker'来做判断了，之前是e.target instanceof Marker

改了以后就可以了，3.7.0 也可以用了。没有报错了

**Comment by qianzhangsheng** [comment]
> > 对，hoverNodeActived那块改成e.target.cfg.type === 'marker'来做判断了，之前是e.target instanceof Marker
> 
> 改了以后就可以了，3.7.0 也可以用了。没有报错了

谢谢大佬

**Comment by kanfashidoufu** [comment]
大佬们 貌似3.7.3又出来这个错误了
