### ISSUE TITLE
更新边edge报错。

### ISSUE THREAD

**Issue by wrh4585** [guozhaolong/wfd-vue#46]
更新边edge报错。
选中边，通过一个颜色选择器选择颜色后，拿到选中边的model，对其中的style的stroke进行赋值，然后调用updataItem方法，不生效。refreshItem()也不生效。最后根绝改变节点属性的方法，拿到边edge的keyShape，然后使用keyShape.attr()对style的stroke进行赋值，在调用refreshItem（）依然不起作用。使用updateItem()时可以生效，但不能传递model值，否则也不生效。但是不传递model值会报source undefined的错误。

**Comment by guozhaolong** [comment]
代码发上来看看

**Comment by wrh4585** [comment]
![image](https://user-images.githubusercontent.com/45685551/91698601-9038e380-eba5-11ea-9db3-c5abe1f74774.png)
![image](https://user-images.githubusercontent.com/45685551/91698722-c2e2dc00-eba5-11ea-8307-9cb1917523ca.png)
主要就是这块的处理逻辑。很奇怪，类似节点改变边和背景色时的实现，但是使用keyShape.attr(),的方式并不生效，后面调用updataItem()方法时，不能传递数据model，否则生效。

**Comment by wrh4585** [comment]
代码的话，拷不出开，敲的话也很慢，结果截个图发现貌似显示不了。。。

**Comment by guozhaolong** [comment]
我看G6源码edge有个updateShapeStyle方法用来改变边的样式，你可以试试，我感觉是你传的style格式不对造成的

**Comment by wrh4585** [comment]
好的，我试试去。style的格式，参照内置边里style的设置，这样应该是没有问题的吧
