### ISSUE TITLE
G6 3.8.0版本，自定义edge报错 

### ISSUE THREAD

**Issue by coldwind6** [guozhaolong/wfd-vue#51]
![image](https://user-images.githubusercontent.com/46366124/94631385-ea3edd00-02fa-11eb-9a5d-b4fb1e8f5645.png)

使用自定义edge**flow-polyline-round**时,报出上面截图错误，换用3.5.2亦是如此，请教一下是哪一环节出的问题，手动拖拽添加edge正常，初始化渲染时报错，拖动节点时报错

**Comment by coldwind6** [comment]
自定义edge中 添加配置属性
update: undefined,

**Comment by guozhaolong** [comment]
我在options里加了一个routeCfg空对象就好了

**Comment by qianzhangsheng** [comment]
> 我在options里加了一个routeCfg空对象就好了


大佬是这里加routeCfg空对象吗？
<img width="570" alt="WX20201104-135310@2x" src="https://user-images.githubusercontent.com/1262247/98074295-1bd03880-1ea5-11eb-9723-4e5bd81bcd48.png">

**Comment by guozhaolong** [comment]
对头
