### ISSUE TITLE
G6 3.8.0中节点拖拽至可视区域外报错

### ISSUE THREAD

**Issue by coldwind6** [guozhaolong/wfd-vue#52]
![image](https://user-images.githubusercontent.com/46366124/94646708-68ae7580-0321-11eb-8cae-07cfb1ed0327.png)

G6 3.8.0版本，当节点被拖拽至可视区域外，辅助线消失后，松开，移动到graph时，报错，然后整体失效

**Comment by guozhaolong** [comment]
我没有复现这个bug，有gif动图操作么？

**Comment by coldwind6** [comment]
![屏幕录制2020-10-09 11 19 49](https://user-images.githubusercontent.com/46366124/95540435-5c15d580-0a23-11eb-8a43-167bab4b05d5.gif)

## g6版本为3.8.0
## 复现步骤：将节点拖动至graph 外侧（下侧等，演示方便，拖动到了左侧），松开鼠标，鼠标移动到graph中时，则报错

**Comment by coldwind6** [comment]
> 我没有复现这个bug，有gif动图操作么？

下一评论中，添加了复现的动图，烦请帮忙定位一下问题

**Comment by guozhaolong** [comment]
没有定位到具体问题，把局部刷新关了就不报错了，在componentDidMount下面加上`this.graph.get('canvas').set('localRefresh', false);`

**Comment by 13029678009** [comment]
单纯的升级一下版本 就有这问题(｀・ω・´)

**Comment by 13029678009** [comment]
<img width="735" alt="WX20201010-110100@2x" src="https://user-images.githubusercontent.com/42032734/95644388-ebd18780-0ae8-11eb-8b86-2b29e31ae103.png">
心态崩了

**Comment by coldwind6** [comment]
> 没有定位到具体问题，把局部刷新关了就不报错了，在componentDidMount下面加上`this.graph.get('canvas').set('localRefresh', false);`

为了用新版本，只能这样了，谢谢🙏

**Comment by coldwind6** [comment]
> <img alt="WX20201010-110100@2x" width="735" src="https://user-images.githubusercontent.com/42032734/95644388-ebd18780-0ae8-11eb-8b86-2b29e31ae103.png">
> 
> 心态崩了，升级后 ，拖动的时候 上一个不能清除掉

也许是issue中提过的问题，关于判断mark点时候的逻辑，移除了Mark

[https://github.com/guozhaolong/wfd-vue/issues/45#issuecomment-683616894](url)

**Comment by guozhaolong** [comment]
> <img alt="WX20201010-110100@2x" width="735" src="https://user-images.githubusercontent.com/42032734/95644388-ebd18780-0ae8-11eb-8b86-2b29e31ae103.png">
> 
> 心态崩了，升级后 ，拖动的时候 上一个不能清除掉

嗯，hoverNodeActived.ts里面将`e.target instanceof Marker`改为`e.target.cfg.type === 'marker'`
