### ISSUE TITLE
开始节点以及结束节点，点中间图标按住无法拖拽，只有点边缘按住才可以拖拽。

### ISSUE THREAD

**Issue by xuyangxy** [guozhaolong/wfd-vue#57]
如题，在画布里面开始节点和结束节点，点中间图标按住时无法拖拽，只有点边缘按住才可以拖拽。

代码：目前最新版，刚拉的代码。
电脑： mac    
浏览器：chrom

**Comment by gotounix** [comment]
我复现了这个BUG，问题在于group.icon 用了path，如果不用path貌似就没有问题。

**Comment by gotounix** [comment]
@xuyangxy 刚发现 Pull requests 里面的那哥们修复了这个 Bug，你可以去用他 fork 的代码，貌似修复了很多东西。

**Comment by xuyangxy** [comment]
@gotounix  好的，我fork一下看看怎么修复的，谢谢
