### ISSUE TITLE
@antv升级以后节点上的point鼠标移上去出现问题

### ISSUE THREAD

**Issue by qianzhangsheng** [guozhaolong/wfd-vue#59]
![zp745-fqeai (1)](https://user-images.githubusercontent.com/1262247/98082728-2cd47600-1eb4-11eb-9105-1d8f23a9964e.gif)

**Comment by guozhaolong** [comment]
Duplicate of #45

**Comment by guozhaolong** [comment]
这个报错了吗？是不是marker类型判断那里的问题？

**Comment by qianzhangsheng** [comment]
> 这个报错了吗？是不是marker类型判断那里的问题？

没有报错

> if (!(e.target instanceof Marker) && !this.graph.get('edgeDragging')) 

下面这里判断是「undefined」
> !this.graph.get('edgeDragging')

**Comment by guozhaolong** [comment]
判断marker已经改了，
Duplicate of #52
