### ISSUE TITLE
在线demo进去是空的

### ISSUE THREAD

**Issue by lzw5399** [guozhaolong/wfd-vue#62]
作者你好，README上面的Online Demo链接进去是空的，能帮忙看一下吗

> https://guozhaolong.github.io/wfd-vue/

![](http://pic.codepie.fun/img/20210108155334.png)

**Comment by guozhaolong** [comment]
我看了一下，这个叫@GoldSubmarine最后贡献过代码，我最近在忙别的事没时间看，应该是他给搞坏了，可能把wfd-vue项目搞坏了更符合他自己项目的意愿吧，我现在没时间弄这个

**Comment by GoldSubmarine** [comment]
目前静态文件没有增加 `/wfd-vue` 前缀，并不是我改错了， `vue.config.js` 文件下的 publicPath 被你注释了，不知道你之前部署是怎么成功的

**Comment by guozhaolong** [comment]
问题是你不应该提交docs里面的代码，既然你提交了就应该保证能用啊，之前能看，现在不能看了 @GoldSubmarine

**Comment by Nayacco** [comment]
npm里有打包docs的命令，我改完package中的代码，要发布docs，自然就执行打包命令，哪还会去检查这个打包命令是否正确？换做是你你会去检查吗？就算我没有检查，你觉得我不严谨，也不能得出我要恶意破坏你项目的结论吧。毕竟这个有问题的打包命令是你写的。

**Comment by guozhaolong** [comment]
错怪兄弟了，对不起，多多包涵，我不是做vue开发的，现在工作很忙也没时间管这项目，我希望如果还有人在用，你能帮大家去看一下，多谢 @GoldSubmarine

**Comment by Nayacco** [comment]
其实我是java后端🤪

**Comment by guozhaolong** [comment]
@GoldSubmarine 我本身也是写java和scala的。。。
