### ISSUE TITLE
运行报错，提示找不到  @antv/g6/src/shape/single-shape-mixin  这个文件

### ISSUE THREAD

**Issue by winken168** [guozhaolong/wfd-vue#7]
These dependencies were not found:

* @antv/g6/src in ./node_modules/_cache-loader@4.1.0@cache-loader/dist/cjs.js??ref--12-0!./node_modules/_babel-loader@8.0.6@babel-loader/lib!./node_modules/_cache-loader@4.1.0@cache-loader
/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.9.0@vue-loader/lib??vue-loader-options!./src/components/Wfd.vue?vue&type=script&lang=js&
* @antv/g6/src/item/item in ./src/item/anchor.js
* @antv/g6/src/shape/single-shape-mixin in ./src/shape/anchor.js

To install them, you can run: npm install --save @antv/g6/src @antv/g6/src/item/item @antv/g6/src/shape/single-shape-mixin

运行报告 ，提示找不到到  @antv/g6/src/shape/single-shape-mixin  这个文件。
请问是不是引用的@antv/g6 版本有问题？ 配置文件里的版本是 "@antv/g6": "^3.1.3",

**Comment by guozhaolong** [comment]
貌似是g6更新版本以后没有src目录只有lib目录了，我更新一下依赖

**Comment by winken168** [comment]
我升级了g6的版本把有src的版本替换就正常了，给你点个赞，真心不错，谢谢！

**Comment by guozhaolong** [comment]
我发现问题了，如果更新到3.3.x版本，里面的依赖类也有变化，所以等我研究一下再升级到新版，目前3.2.4是ok的
