### ISSUE TITLE
大佬，想请教您写的源码问题，我看代码里的插件比如AddItemPanel，都不是g6里提供的，请问您是自己写的吗?

### ISSUE THREAD

**Issue by Simmon12** [guozhaolong/wfd-vue#71]
比如 这个AddItemPanel，请问您为什么这么写，您怎么就知道这个类里需要有这几个方法呢?
![image](https://user-images.githubusercontent.com/19617199/133397812-10a2773f-de38-48c3-8bd6-8def6eaa569e.png)

**Comment by guozhaolong** [comment]
通过看官方的插件和源码知道的。。。这个就一个initPlugin有用

**Comment by Simmon12** [comment]
明白了，多谢，是哪个源码？是G6的源码吗? 还是g6-editor的源码？

**Comment by guozhaolong** [comment]
g6的，我都好久没关注这个项目了，手里事太多了

**Comment by Simmon12** [comment]
明白了，多谢
