### ISSUE TITLE
为什么我拉下来运行后连线不是特别灵敏？

### ISSUE THREAD

**Issue by guanpenghui1993** [guozhaolong/wfd-vue#73]
https://user-images.githubusercontent.com/25782424/137419177-97b5ad76-c65b-49eb-a292-2fbfabb92fb8.mp4

![微信图片_20211015094426](https://user-images.githubusercontent.com/25782424/137419331-c909f805-496d-4152-a69f-850c9f995d28.png)

鼠标指到上面是移动，连线得触发点特别难以聚焦？

**Comment by guanpenghui1993** [comment]
@guozhaolong

**Comment by guozhaolong** [comment]
应该是锚点的类型判断那里报错了，这个问题我记得在wfd里面解答过，目前这个项目已经停止维护了，你只能自己去翻一下issue啦。。。

**Comment by guanpenghui1993** [comment]
> 应该是锚点的类型判断那里报错了，这个问题我记得在wfd里面解答过，目前这个项目已经停止维护了，你只能自己去翻一下issue啦。。。

好的，我找找
