### ISSUE TITLE
> @gzhanghui老哥，请教下，更新至4.1以上版本以后

### ISSUE THREAD

**Issue by huangtangtang** [guozhaolong/wfd-vue#77]
> @gzhanghui老哥，请教下，更新至4.1以上版本以后
> 
> `shape\anchor.js`中以下代码
> 
> ```
> import { shapeBase } from '@antv/g6/lib/shape/shapeBase';
> import Shape from '@antv/g6/lib/shape/shape';
> ```
> 
> 和`item\anchor.js`中以下代码：
> 
> ```
> import editorStyle from '../util/defaultStyle';
> import Item from '@antv/g6/lib/item/item';
> import { deepMix } from '@antv/util';
> 
> export default class Anchor extends Item {
>   ...
> ```
> 
> 如何升级呢？
> 
> 直接`import Item from '@antv/g6`不能用，`shapeBase `也没有。
> 
> 谢谢。
可以稍微看一下g6的目录解构
import { shapeBase } from '@antv/g6-core/lib/element/shapeBase';
import Shape from '@antv/g6-core/lib/element/shape';

_Originally posted by @gzhanghui in https://github.com/guozhaolong/wfd-vue/issues/68#issuecomment-1119218031_

**Comment by huangtangtang** [comment]
These dependencies were not found:

* @antv/g6/lib/item/edge in ./src/shape/subProcess.js
* @antv/g6/lib/item/item in ./src/item/anchor.js
* @antv/g6/lib/item/node in ./src/shape/subProcess.js

**Comment by huangtangtang** [comment]
x

**Comment by zhanghui-space** [comment]
> shapeBase

```js
import { shapeBase } from '@antv/g6-core/lib/element/shapeBase';
import Shape from '@antv/g6-core/lib/element/shape';
```

package.json
```json
 "dependencies": {
    "@antv/dom-util": "2.0.2",
    "@antv/g-canvas": "^0.4.12",
    "@antv/g6": "^4.2.6",
    "@antv/g6-core": "^0.2.6",
    "@antv/util": "~2.0.9",
 }
```



package

**Comment by huangtangtang** [comment]
您好，我现在的问题是: 按照你给的配置改完以后，
同时我也修改了以下三个代码
```
const Node = require('@antv/g6-core/lib/item/node');
const Edge = require('@antv/g6-core/lib/item/edge');
import Item from '@antv/g6-core/lib/item/item';
```
项目才可以正常启动，但是页面报错： 
![image](https://user-images.githubusercontent.com/52057758/187364333-fd21370d-8842-41c0-8df0-65f772f920e4.png)

 好像是找不到G6 ， 项目中 import G6 from '@antv/g6/lib'; 需要改吗？

**Comment by zhanghui-space** [comment]
> 您好，我现在的问题是: 按照你给的配置改完以后， 同时我也修改了以下三个代码
> 
> ```
> const Node = require('@antv/g6-core/lib/item/node');
> const Edge = require('@antv/g6-core/lib/item/edge');
> import Item from '@antv/g6-core/lib/item/item';
> ```
> 
> 项目才可以正常启动，但是页面报错： ![image](https://user-images.githubusercontent.com/52057758/187364333-fd21370d-8842-41c0-8df0-65f772f920e4.png)
> 
> 好像是找不到G6 ， 项目中 import G6 from '@antv/g6/lib'; 需要改吗？

需要添加util包  这个报错说的是没有util.deepMix这个方法

**Comment by huangtangtang** [comment]
> > 您好，我现在的问题是: 按照你给的配置改完以后， 同时我也修改了以下三个代码
> > ```
> > const Node = require('@antv/g6-core/lib/item/node');
> > const Edge = require('@antv/g6-core/lib/item/edge');
> > import Item from '@antv/g6-core/lib/item/item';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 项目才可以正常启动，但是页面报错： ![image](https://user-images.githubusercontent.com/52057758/187364333-fd21370d-8842-41c0-8df0-65f772f920e4.png)
> > 好像是找不到G6 ， 项目中 import G6 from '@antv/g6/lib'; 需要改吗？
> 
> 需要添加util包 这个报错说的是没有util.deepMix这个方法

大佬好，我确实也加了util包，可是页面就是报上面的错，
package.json
```
    "@antv/dom-util": "2.0.2",
    "@antv/g-canvas": "^0.4.12",
    "@antv/g6": "^4.2.6",
    "@antv/g6-core": "^0.2.6",
    "@antv/util": "~2.0.9",
    "@antv/matrix-util": "2.0.7",
```
![image](https://user-images.githubusercontent.com/52057758/187376245-cc2f1cd6-bedd-470f-b317-d27cf99fe525.png)
望指教，谢谢~

**Comment by zhanghui-space** [comment]
需要找到使用这个方法的文件  
```js
 -   G6.Util.deepMix
 +   import Util from '@antv/util'
     Util.deepMin
  
```
