### ISSUE TITLE
IE9是否可支持呢

### ISSUE THREAD

**Issue by ljt138** [guozhaolong/wfd-vue#8]
大牛：请教一下
google正常
IESCRIPT1028: SCRIPT1028: Expected identifier, string or number
chunk-vendors.js (1331,1)

**Comment by woleicom** [comment]
https://g6.antv.vision/zh/docs/manual/FAQ/supportIE
请查看antv G6文档

**Comment by guozhaolong** [comment]
> https://g6.antv.vision/zh/docs/manual/FAQ/supportIE
> 请查看antv G6文档
没毛病
